FROM node:18-alpine as build
WORKDIR /opt/app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build



FROM node:18-alpine
WORKDIR /opt/app
COPY package.json ./
RUN  npm run install --only=prod
COPY --from=build /opt/app/dist/app ./dist
CMD [ "node", "./dist/main.js"]